# Generated by Django 5.0.6 on 2024-11-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0003_alter_brand_description_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_com.cartitem'),
        ),
    ]
